# Lightman's Currency Common Configurations

[villagers]
	# Whether the wandering trader will have additional trades that allow you to buy misc items with money.
	addCustomWanderingTrades = true
	# Whether the banker villager profession will have any registered trades.
	# The banker sells Lightman's Currency items for coins.
	addBanker = true
	# Whether the cashier villager profession will have any registered trades.
	# The cashier sells an amalgamation of vanilla traders products for coins.
	addCashier = true

	[villagers.modification]
		# Whether vanilla villagers should have the Emeralds from their trades replaced with coins.
		changeVanillaTrades = true
		# Whether villagers added by other mods should have the Emeralds from their trades replaced with coins.
		changeModdedTrades = true
		# Whether the wandering trader should have the emeralds from their trades replaced with the default replacement coin.
		changeWanderingTrades = true
		# The default coin to replace a trades emeralds with.
		# May separate and define villager type specific entries by adding multiple items separated by '-' with region
		defaultEmeraldReplacementItem = "lightmanscurrency:coin_emerald"
		# List of replacement coin overrides.
		# Set to empty to force all professions to fall back to the default coin (Elandrian Aur / Emerald Coin).
		professionEmeraldReplacementOverrides = []
